name: Deploy to ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: docker build -t production-cicd-demo .

      - name: Tag Docker image
        run: |
          docker tag production-cicd-demo:latest \
          ${{ steps.login-ecr.outputs.registry }}/production-cicd-demo:latest

      - name: Push Docker image to ECR
        run: |
          docker push \
          ${{ steps.login-ecr.outputs.registry }}/production-cicd-demo:latest

      - name: Download task definition
        run: |
          aws ecs describe-task-definition \
          --task-definition production-task \
          --query taskDefinition > task-definition.json

      - name: Fill in new image ID
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: flask-container
          image: ${{ steps.login-ecr.outputs.registry }}/production-cicd-demo:latest

      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: production-service
          cluster: production-cluster
          wait-for-service-stability: true
